import type { Metadata } from "next";
import {Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/sections/navbar";

import localFont from 'next/font/local'



// const spaceGrotesk = Space_Grotesk({
//   subsets: ["latin"],
//   weight: ['400', '500']
// })

const cabinetGrotesk = localFont({
  src: [
    {
      path: '../../public/fonts/CabinetGrotesk-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/CabinetGrotesk-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-cabinet',
});

export const metadata: Metadata = {
  title: "Repository",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.className} antialiased`}
      >
        <Navbar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
